### ISSUE TITLE
Error after reboot...power switch again

### ISSUE THREAD

**Issue by bartch** [theyosh/TerrariumPI#104]
As i wrote before, everything was working fine. Since we are currently starting with the new terrarium we switched of the pi till today...now after booting the software continuously reboots. The Traceback is as follows:

> Traceback (most recent call last):
>   File "/home/pi/TerrariumPI/terrariumPI.py", line 17, in <module>
>     terrariumEngine = terrariumEngine()
>   File "/home/pi/TerrariumPI/terrariumEngine.py", line 82, in __init__
>     self.environment = terrariumEnvironment(self.sensors, self.power_switches, self.weather, self.is_door_open, self.config.get_environment)
>   File "/home/pi/TerrariumPI/terrariumEnvironment.py", line 30, in __init__
>     self.load_environment()
>   File "/home/pi/TerrariumPI/terrariumEnvironment.py", line 132, in load_environment
>     self.__check_available_power_switches()
>   File "/home/pi/TerrariumPI/terrariumEnvironment.py", line 142, in __check_available_power_switches
>     del(self.light['power_switches'][switchid])
> TypeError: list indices must be integers, not str

**Comment by theyosh** [comment]
Hi,

sorry to hear that you run in to issues. This is a somewhat known upgrade issue. If you are restarting your terrarium setup, the easiest fix is the remove or rename the setting.cfg file to something else.

Then it will start in a clean setup. When you add your sensors and switches, the history data is still there.

Fixing this in code is rather hard, and only for one version upgrade. So removing the settings.cfg file is the fix for now.
