### ISSUE TITLE
Multiple environments of the same type

### ISSUE THREAD

**Issue by jornobe** [theyosh/TerrariumPI#207]
First of all, this project is great! Using it to control most parts of my tropical enclosure. 

While being able to add multiple sensors of the same kind (e.g. 4 different temperature sensors), there is only 1 environment they can be used in. 

In my enclosure the left side is intentionally colder than the right side (2.4m apart). Having multiple “temperature” environments would allow the use of the different sensors to trigger different relays and getting this difference in temperature under control.

Same actually applies for water that is being heated. The temperature sensor shows the actual value and an additional environment for this would be great as well to control the heating elements.

If it would be possible to have this implemented then being able to set a custom name for the environment would be nice as well. Avoids ending up with multiple “Temperature” names but no indication what parts they actually control.

**Comment by theyosh** [comment]
Damm, it is getting more complicated by the minute :P 

This is also a valid setup, and I see why for you multiple environments is the solution. And I think it is very nice to support this.

But for now, I can only refer to #202 . I am thinking of making it possible. But being a big overhaul of the code, it will be done in a slow pace. I am currently refactoring code in order to make the switch to multiple environments easier.

I close it now, and advise to subscribe to #202 to get updates. That issue will stay open so I can post progress.
