### ISSUE TITLE
Email notifications sent to invalid recipient address

### ISSUE THREAD

**Issue by jornobe** [theyosh/TerrariumPI#211]
Sending email notifications to a recipient address in the format "firstname@domain.org" results in messages being addressed to "firstname+terrariumpi@domain.org"

"firstname.lastname@domain.org" works fine as recipient address using the same relay server settings.

**Comment by theyosh** [comment]
Not sure what the issue is? Because the + is used for 'tagging' the mail so you can easily created filters in your own mail client. And it should be valid.

all mail at firstname+whatever@domain.org should just be delivered at firstname@domain.org. If that is not the case, the receiving mail server does not support this. Which is a bit strange, as almost any mail server should accept it.

If you have mail server error logging, maybe it gets clearer...

**Comment by jornobe** [comment]
Understand the idea. The tagging doesn’t seem to work on my @gmail.com target address

**Comment by jornobe** [comment]
Was an SMTP sever issue... changed to gmail relay and it works as expected!

**Comment by theyosh** [comment]
Cool! Then I am closing this issue now.
