### ISSUE TITLE
Strange DHT22 error (they Not THIS Bad are they?)

### ISSUE THREAD

**Issue by wes1007** [theyosh/TerrariumPI#272]
been having some intermittent issues with DHT22 and DS18B20 temperature/Humidity sensors. Cable lengths are all shorter than 3.5m. The DS18B20 seem to be fine though as i get readings all the time.

THe DHT22s however seem to get none readings randomly. Sometimes come back and sometimes dont. HardReboots seem to help where i generally get 3 readings out of 4. then it starts going downhill. Runing sudo reboot seemed to drop all the DHT22s. 

Im concerned about the updates exceeding the timeout of 30s. Not sure if that has something to do with it:
`Updating took to much time. Needed 43.68746 seconds which is 13.68746 more then the limit 30`

DHT22 - InternalTemp/Humidity - Pin 13
DHT22 InternalTemp/Humidity Pin12

Logs Attached:

Terlog-From Hardreset Pi (pulled usb power cable out)
Terlog2-From Hard reset
Terlog3-From Hard Reset
Terlog4-From Hard reset
Terlog5- From Reboot Via Sudo Reboot
Terlog6- From Hard Reset - Pin 13 (internal Temp/ Humidity DHT22 )removed from the sensors setting page before the reset
Terlog7-From Hard Reset - Pin 13 added back in the setting page and Pin 12 (Intake Temp/Humidity DHT22) removed From sensors setting page before reboot. After the reboot i realized the Temperature environment senor settings had been lost when pin 13 was removed. So i fixed that.
[TerLog5SudoReboot.txt](https://github.com/theyosh/TerrariumPI/files/2938281/TerLog5SudoReboot.txt)
(https://github.com/theyosh/TerrariumPI/files/2938282/TerLog7RemomePin12FixEnivro.txt)
(https://github.com/theyosh/TerrariumPI/files/2938283/TerLog6RemovePin13.txt)
[TerLog.txt](https://github.com/theyosh/TerrariumPI/files/2938284/TerLog.txt)
[TerLog2.txt](https://github.com/theyosh/TerrariumPI/files/2938285/TerLog2.txt)
[TerLog3.txt](https://github.com/theyosh/TerrariumPI/files/2938286/TerLog3.txt)
[TerLog4.txt](https://github.com/theyosh/TerrariumPI/files/2938287/TerLog4.txt)

**Comment by jornobe** [comment]
Because they are not providing constant trustable readings I have moved away from the DHT22 sensors. 

Now use the RPI3 1-wire host adaptor and SWE3 humidity/temperature sensors from Sheepwalk Electronics. Solid readings 24h a day! These sensors hook up using standard UTP cables to the 1-wire host adaptor which itself plugs onto the Pi directly.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by wes1007** [comment]
Damn. not exactly what i was wanting to hear. I have a bunch of SI7021 Temp/humidity sensors that run over I2C but my concern is that 3m of cable might not be idea with them (that and ill have to make a new breakout board :( )

I have a DHT22 running on a nodemcu tied into openhab for home automation thats been working pretty flawlessly for a while now. maybe i just got lucky with that one?

**Comment by wes1007** [comment]
@theyosh anything to add to this beside chuck the DHT22s in the bin?

**Comment by theyosh** [comment]
I am not sure about this. I do experience that DHTXX are not that stable. I have just one for testing, but that is failing about 30% of the time according to my logfiles. So that is 1/3 of all measurements. And that is not that stable.

Also, I do get the feeling, that it is a bit sensible to power fluctuations as well that it needs somehow to much power when it needs to measure.

So, my experience is that DHTXX are not useful. I also recommend to use something like the SWE3 from Sheepwalk. That uses it own bus and different sensors. Which are a bit more expensive, but I have it running now for couple of years already without any issues. It is way more stable.

I do had some sensors over 2 meter cable with I2C. It did work, until some water came into the sensors ;). But this is also for hard to judge. I do not have that much hardware experience. But, I would just say, try one with 3M cable. And see how it works. If it stays stable for lets say a week, you could try to use it in production.

And do you see power errors when you run `dmesg`?

Voltage normalised (0x00000000)
Under-voltage detected! (0x00050005)

**Comment by theyosh** [comment]
Ok, I close this now, as there is not much that I can do about this. DHTXX is cheap and nice for some small projects. But 24/7 is just to much for those sensors....
