### ISSUE TITLE
Support Request: BrightPi Camera Light

### ISSUE THREAD

**Issue by fenyx13** [theyosh/TerrariumPI#280]
Hi TheYosh,
Would it be possible to control BrightPi from TerrariumPi?

BrightPi: https://uk.pi-supply.com/products/bright-pi-bright-white-ir-camera-light-raspberry-pi
BrightPi GitHub: https://github.com/PiSupply/Bright-Pi
Python library: https://github.com/jritter/brightpi

Thanks.

**Comment by theyosh** [comment]
Hmm, the camera itself is not the issue. But how would you see this? Because the code can control all the leds individual. But I do not think I will support that. That will add to much extra code.

So, what I can think off, is that it has so toggle with the mail lights in opposite state. So light on, IR off. And lights off, IR on.

So, some out of the box thinking here. What if you add them as two independent dimmers switches? As the example code suggest, they can be dimmed. So then you have a Bright white and IR dimmer for the camera. And then at the environment page, you can use the bright white dimmer for daylight power switch, and the IR dimmer for the night power switches. As they are dimmers, they will go slowly on and off.

**Comment by theyosh** [comment]
I ordered a few of them. So I can see what is possible.

**Comment by theyosh** [comment]
I have added support for this. For now ONLY white lights or IR lights are supported.

Enter address value 70 for normal white. Or 70,ir for IR lights. Using both will give errors due to device sharing. I have to look into that.

**Comment by theyosh** [comment]
Any update on this?

**Comment by fenyx13** [comment]
Sorry for not replying earlier. In the middle of moving to a new place. 
I will find my PI tomorrow and test it out

**Comment by theyosh** [comment]
Closing, due to no response. Can be opened any time when there are updates
