### ISSUE TITLE
Update to installation instructions for Raspbian Stretch full

### ISSUE THREAD

**Issue by tvStatic** [theyosh/TerrariumPI#290]
I was able to successfully install TerrariumPI on Raspbian Stretch Full. Hardware was a Raspberry Pi Zero W.

I had to do the following to get past issues I encountered while installing.

- Increase the swap file size to 512MB, per the instructions in [this stack exchange answer](https://raspberrypi.stackexchange.com/questions/70/how-to-set-up-swap-space).
- Reinstall pip per the instructions in [this stack overflow answer](https://stackoverflow.com/a/37531821/695786)

After doing that and otherwise following the install instructions as normal, I got a system running successfully. The only other possible deviations in my setup were that I did not remove the "not needed programs" when prompted.

**Comment by theyosh** [comment]
Cool, thanks for the details. The swap issue can maybe fixed by the installer. That you need a newer pip is a bit strange. I cannot see why that should be different then other Pis. As the OS is the same.

So, I will look into the swap file issue, and see if I can increase it during installation. Thanks for the information
