### ISSUE TITLE
Miflora light sensor too noisy

### ISSUE THREAD

**Issue by duenni** [theyosh/TerrariumPI#293]
Hi,

does anyone else experience a really noisy "average light" sensor from a MiFlora?
<img width="1313" alt="Bildschirmfoto 2019-05-23 um 19 27 02" src="https://user-images.githubusercontent.com/4258185/58273333-c5466b80-7d90-11e9-9579-6b2e72c3c8b6.png">
It's really unusable in this state. The values differ sometimes >1000 lux within some minutes with no change in the environment. Also when it's really dark, the values jump between 0 and 300 lux, which is kind of funny. Is this a problem related to Miflora (is my Miflora faulty and should be replaced?) or is this some issue with TerrariumPi and how it gets the data?
Also there are two y-scales, one for Lux one for uW/cm^2. When setting the "Limit Max" value in the sensors settings, it seems to correspond to the "UVB" value in the graph. There is also an "UVA" value which is the lower limit. What sense does that make? Why are there two scales?
Thanks!

**Comment by theyosh** [comment]
Hmm, 

my problem is that I use existing libraries and code. So I can not tell why this is happening. I do see the same thing:

![image](https://user-images.githubusercontent.com/8080177/58438689-60607d80-80d0-11e9-8d29-06318fbc063f.png)

But I have also added a UV Index sensor, which uses the values of UVA and UVB and show that value on the graph. Therefore we have two scales and no min and max values. I know this is a bit odd comparing to other graphs, but you can measure lights in different ways,UV and Lux, so I thought this is the best way to show it in a single graph

But as you can see, my UV Index is also spiky. This is because my UV sensors are also spiky. And as I am not able to measure the power over the lines, or bluetooth packages, I must conclude that this is the normal way. I have thought of making the data more smooth, that involves some math which I am not that good in.

So for now, I have accepted this behaviour as expected and have no Idea how to change.

**Comment by theyosh** [comment]
Closing due to no more response....
