### ISSUE TITLE
Translate

### ISSUE THREAD

**Issue by vanessa2013** [theyosh/TerrariumPI#34]
What can I do if I can not find all words or phrases in Poedit and I can not translate them? Thx

**Comment by vanessa2013** [comment]
Something else, I can not change the password, it will not be saved

**Comment by theyosh** [comment]
I can change my password. So I cannot reproduce your problem. Please use normal characters and numbers first.

If you are missing translations, please make a screenshot of what should be translated. Else I do not understand your question.

I can say that all Weather forecast is non translatable due to the fact it comes from an external API.

**Comment by vanessa2013** [comment]
Hi, I've marked the translation to red, I can not find it in Poedit. timer would be correct but "Timer". sensor> "Sensor" ....

Another question. Why does the light turn at 06:00 when I set it from 18: 00-12: 00 I have to expand every day the time :-)
![unbenannt](https://user-images.githubusercontent.com/31970192/32018299-c33f90b4-b9c9-11e7-8ebf-9f236ffd9cb2.png)

**Comment by theyosh** [comment]
Ok, translation is fixed in latest version: https://github.com/theyosh/TerrariumPI/commit/3ac7a592fc70a81c074ed5ed15ef94479ce6196e

With `git pull` and clearing your browser cache should be enough to see the translation if you reload the web interface.

Time issue takes more time. I have to test it.

**Comment by theyosh** [comment]
Setting time from 18:00 till 12:00 the next day? So it will be running during the night and next morning? Is this correct?

**Comment by vanessa2013** [comment]
Yes correct.
Unfortunately, it does not take the whole translation, that is, large and small letters

**Comment by vanessa2013** [comment]
Hi, have you seen this already?

![unbenannt](https://user-images.githubusercontent.com/31970192/32138647-641565cc-bc36-11e7-93ca-db5364e952e2.png)

**Comment by theyosh** [comment]
That is correct! Shifting from sumer time to winter time. Tomorrow it is back to 18 hours :P

**Comment by vanessa2013** [comment]
Ok, then everything works great again :-) Thank you
