### ISSUE TITLE
CPU overload

### ISSUE THREAD

**Issue by jeff26300** [theyosh/TerrariumPI#384]
Hello,

My CPU is constantly overloaded and has a permanent warning. Is it normal?

![Capture d’écran 2020-05-02 à 13 49 54](https://user-images.githubusercontent.com/57871568/80863356-f9522e00-8c7b-11ea-9555-abe8f7d51b5b.png)

Thanks,

Jeff

**Comment by jaysalazar** [comment]
Do you happend to have a CPU fan installed? I have a Pi3 w/nofan and Pi4 w/fan in a warm garage and the Pi4 w/fan helps alot.

**Comment by theyosh** [comment]
Hmm, is it really overloaded... I think it is something different.

Are you using 1wire devices through GPIO? It not, you can disable it by changing the file: /boot/config:

`sudo nano /boot/config'

And add a '#' for the line 'dtoverlay=w1-gpio'

Then reboot it. This will stop polling for 1Wire. I have seen that it could increase the load a bit.

Else you have to look with top command to see what is taking a lot of CPU: https://www.lifewire.com/linux-top-command-2201163

And about temperatures, my Pi 4 is running at 60C which is fine for me. My Pi3 is doing 55C So that is fine for me, and do not see that as a problem.

So could you look with top command to see what is using a lot of CPU?

**Comment by jeff26300** [comment]
Thanks @theyosh , I have indeed a 1wire for the hearing sensor. I run the command you suggested and this is what I got: 
![Capture d’écran 2020-05-05 à 15 10 11](https://user-images.githubusercontent.com/57871568/81069767-a3cb8a80-8ee2-11ea-9a50-f760b7371835.png)

@jaysalazar , I have currently no fan on my pi zero

Thanks guys!

**Comment by theyosh** [comment]
Ok, then the 1wire is not causing this.
Then I see two python processes running. And my software should only have one python process. So what you can do now, based on the information of top. Run the following command:

`ps fax | grep 1823` and see what the output is. The number 1823 is the number in the first column on the image above. That is also the process which takes the most cpu.

So the then you can what both python process are. Repeat the above for all the python processes.

**Comment by jeff26300** [comment]
that's what I got for the main one :
![image](https://user-images.githubusercontent.com/57871568/81101921-1c484080-8f0f-11ea-93d9-8c6b41d93467.png)

**Comment by theyosh** [comment]
Hmm, you last picture is not correct. I need the line where it starts with that number 3776. Now you have only listed the process 'grep' which is not the right line.

A total different option can be:

1. Do a `git pull`
2. Rerun the installer as you have done with the normal installation
3. Reboot

Then we now for sure you have the latest software with the latest libraries. If that is solving the issue, then it will be hard to figure out how it started.

**Comment by jeff26300** [comment]
At the end we decided to reinstall the system and everything is now working fine :)
Thanks for your support! I close this issue
