### ISSUE TITLE
Environtment Settings Not Turning Off Switch

### ISSUE THREAD

**Issue by jaysalazar** [theyosh/TerrariumPI#385]
![Environment Settings](https://user-images.githubusercontent.com/63948569/80922418-e00bb900-8d31-11ea-9e23-c120e6a5853f.PNG)
Hello, first I want to say how awesome TerrariumPI is, great job to theyosh for all your hard work and ongoing support.

I have an issue that may be configuration related so help from anyone would be much appreciated.

I setup my temp sensor with Alarm Min = 70F and Alarm Max = 78F, I configured my Environment settings to turn on a switch (connected to cool air duct) to come on when temps go over 78F which actaully works. The problem is that when the temp comes down below 78F the switch never turns off. I have attached my settings, the switches are not in "overide mode" and I have tried restarting.

Any ideas?

![Dashboard](https://user-images.githubusercontent.com/63948569/80922233-7e971a80-8d30-11ea-89ef-8b245b93a276.PNG)
![Temp Settings](https://user-images.githubusercontent.com/63948569/80922235-822aa180-8d30-11ea-98a7-a2f82cc9d630.PNG)

**Comment by theyosh** [comment]
It will shutdown when it gets below the min value. So when it get to hot, it will cool down until the min value. Then it stops, and waits till the temperature is above the max value. 

So if you want to stay the temperature about 78F, you should use 78F as max, and 77F or 76F as min value.

**Comment by jaysalazar** [comment]
I adusted the min value and it's working as designed, thank you for your prompt response! 

Quick question, I get the following warnings, I think they have been addressed here in the past. I assume they are safe to ignore?

![image](https://user-images.githubusercontent.com/63948569/80924169-50b7d300-8d3c-11ea-90b6-9be6257371a9.png)

**Comment by theyosh** [comment]
Those messages are there, because the change in value is more then the allowed change in value in 1 measurement. Per sensor you can give a value what is the max difference per measurement.

Some sensors are not that stable and can sometimes give strange values. So when the change is more then the entered value at the sensor, the measurement is ignored. But after 5 times, it looks like the new measured values are correct and will be used.

This can happen when you turn on a heater which is capable of heating up pretty fast.

So if the measured values are somewhat valid to the conditions in your terrarium. you can just ignore them. If the values are not correct, and the sensor is really broken, a hardware replacement is needed.

**Comment by jaysalazar** [comment]
Thank you for the explanation, I will close this issue now.
