### ISSUE TITLE
[FEATURE]: Add switches before and after taking an image with the webcam

### ISSUE THREAD

**Issue by npinter** [theyosh/TerrariumPI#468]
I'm using Pi Camera IR-Cut (Sensor OV5647), connected via the RPiCam port. 
![image](https://user-images.githubusercontent.com/34959927/95835404-77902180-0d3e-11eb-9344-2cc2c00aa485.png)

Only direct sunlight reduces resistance of the light dependent resistors (LDR) enough to deactivate the LEDs. Due to that, in darker conditions (f.e. in a room) both LEDs stay always on and really heating up (which is also a waste of energy). 

I've removed both LDRs and added a NPN transistor (BC337-40) as well as a 1k Ohm resistor to control both LEDs via GPIO. 
![image](https://user-images.githubusercontent.com/34959927/95842102-6e0ab780-0d46-11eb-83a3-0b97cfed41d8.png)
![image](https://user-images.githubusercontent.com/34959927/95844711-816b5200-0d49-11eb-988a-480c29e61885.png)

**Feature request:** The possibility to set switches before and after taking a picture with the webcam (f.e. IR LEDs on, take picture, IR LEDs off). I'm going to hard code it, but it would be nice if one is able to setup this simply in the UI! 

**EDIT:**
That was easier than I've previously thought: https://github.com/npinter/TerrariumPI/commit/c1015de389a604ec59da553527774c930188a0a3

**Comment by theyosh** [comment]
Hi, sorry for the late reply, but this is a great hack! I use this one also, and noticed the heat also... But this not bother to much.

So, I added this option as a setting. You can now add ',[GPIO PIN]' to the address: rpicam. So then you get the final address like: rpicam,22 where 22 is the physical pin number. https://github.com/theyosh/TerrariumPI/wiki/Hardware#gpio-power-saving

But, can I ask you then to make a small schema (with fritzing) how the hardware is hooked up? So what kind of resistor. So that I can add that to the power management wiki page. So other people can also try this.

I used a different approach. But the result should be the same. Could/would like to test it?

**Comment by theyosh** [comment]
Hi, did you have time to test this solution? And do you have time to make a small schema of the resistor and wiring it to the Pi?

**Comment by npinter** [comment]
Wow nice thank you! I have to test this! Sorry for the late reply, too ;)

**Comment by theyosh** [comment]
Hi, did you had time to make a small schema? If it is easier, just make a small drawing, and I create the schema in fritzing?

I really would like to add this hack to the Wiki.

**Comment by theyosh** [comment]
any updates?

**Comment by npinter** [comment]
Sorry!! I'm pretty busy right now, but I'll have some spare time in the next few days to finally test it and create some kind of soldering scheme :)

**Comment by npinter** [comment]
Sorry for the delay (again).. here is the scheme. fritzing was to complicated so I just used my pictures from above!

![RPi_Cam_IR-Cut_mod](https://user-images.githubusercontent.com/34959927/104139005-a737df80-53a8-11eb-977e-12cdd32e6ef2.png)

**Comment by npinter** [comment]
Sorry for the delay (again).. here is the scheme. fritzing was too complicated so I just used my pictures from above!
![RPi_Cam_IR-Cut_mod](https://user-images.githubusercontent.com/34959927/104139148-9fc50600-53a9-11eb-899f-ce2d594ec046.png)
