### ISSUE TITLE
[BUG]: Interface Can't Be reached after update 3.9.9

### ISSUE THREAD

**Issue by captianboat** [theyosh/TerrariumPI#496]
**Setup:**
 - Python version: 3
 - Raspberry PI: 4

Interface Can't Be reached after update 3.9.9
so i try format SD card and reinstall is still not working 

**Screenshots**
![image](https://user-images.githubusercontent.com/74257775/103163375-dc342600-482f-11eb-8d45-66d0847d2c75.png)
![image](https://user-images.githubusercontent.com/74257775/103163383-ea824200-482f-11eb-8a82-1e8810f9e878.png)

**Comment by theyosh** [comment]
run the following command and it should run again: `sudo pip3 install gevent==20.9.0` and then restart. It appears the latest Gevent has some issues

**Comment by theyosh** [comment]
Made a ticket for gevent: https://github.com/gevent/gevent/issues/1733

**Comment by captianboat** [comment]
it's working now 
but i can't save environment setting :(

**Comment by WorriedTitan** [comment]
Thank you, this worked for me

**Comment by theyosh** [comment]
This issue is fixed with a new Gevent version. But that version has also still a bug with the picamera which is harder to fix: https://github.com/gevent/gevent/issues/1735

So the installer is still fixed on the latest working version 20.9.0

@captianboat Is it also working for you? Can we close this issue?

**Comment by captianboat** [comment]
@theyosh it's work Thank you :)
