### ISSUE TITLE
[FEATURE]: translated default values for notifications messages

### ISSUE THREAD

**Issue by kebs19** [theyosh/TerrariumPI#509]
When you install TerrariumPI and select a language different than English, the page System>Notifications, in the Messages section you see "trigger" strings are still in English and the "Title" and "Message" forms presents English messages as default.

**Comment by kebs19** [comment]
![20210115_045709](https://user-images.githubusercontent.com/54775632/104697202-2a7d6c00-56ee-11eb-8f84-105c28f0d404.jpg)

Here you can see that part of the interface is on Portuguese (Mensagem, título, serviço) but trigger strings and the default messages are in English.

Using TerrariumPI 3.9.9, on a raspberry Pi Zero W.

**Comment by theyosh** [comment]
I made the Trigger names translatable. The input fields for Title and Message are not translatable.  This is because you can fill out your own message in your own language.

Also there is not much documentation about this, so I will leave the %raw_data% as default, as this will give all the options that are available to use in your message. So, use email with %raw_data% to see all the variables that are available. And then use the ones you want.

**Comment by kebs19** [comment]
That's wonderful! I'll start to review the code and we talk again soon.
I'm planning to sign up for a micropython course, I think it will help me get a place to start this language. I'm coming from Arduino (and it's C-based language) so it's gonna be quite a big challenge :)

**Comment by theyosh** [comment]
Can we close this issue?

**Comment by kebs19** [comment]
Sure, closing it.
