### ISSUE TITLE
Is that possible part 2

### ISSUE THREAD

**Issue by vanessa2013** [theyosh/TerrariumPI#51]
I think that would be a good option to dispense with all the cables?

https://electronics.semaf.at/NodeMCU-v2-ESP8266

**Comment by theyosh** [comment]
I like the idea, but then I need to support 100+ devices. So that is not an option. Also this is wifi, but there is also Zigbee, XWave, and other wireless networks. That get all to expensive and difficult.

But I updated my software (beta) so that it is possible to at least read out remote temperature and humidity sensors from a second Raspberry PI running TerrariumPI. If both Pi's are on the same netwerk, you can combine them to one single TerrariumPI.

And maybe in the future more remote API's will be supported. But for now I close this issue.

A first attempt I did was using: https://getchip.com/pages/chip . This can also run Python code and read out DHTXX sensors. And has build in WiFi.

**Comment by vanessa2013** [comment]
Ok Thx.
