### ISSUE TITLE
Switch off heating with door control

### ISSUE THREAD

**Issue by vanessa2013** [theyosh/TerrariumPI#54]
Is it possible to switch off the heating with the door sensor when the door is open and when the door is closed again switch it on again (as with the sprayer).

**Comment by theyosh** [comment]
This is still open to decide...

**Comment by theyosh** [comment]
The problem with this is that I have to keep track of the heater state. And that is a bit difficult.

The sprayers does also work a bit different. The sprayer will not START to spray when the door is open. But when the sprayer is started, it will not stop when the door is opened. So it will not interrupt the sprayer when actual spraying.

So, what is possible, is to make an option, that the heater will shutdown when you open the door, and that the heater stays out when the door closes again. Due to temperature drop in time, the heater will start when it gets below the min alarm. So that is an option.

**Comment by theyosh** [comment]
No need anymore
