### ISSUE TITLE
[BUG]: Can't add Telegram or Pushover notifications

### ISSUE THREAD

**Issue by ntfd0** [theyosh/TerrariumPI#588]
**Setup:**
- Python version: 3
- Raspberry PI: 4b

**Describe the bug**
Trying to add Telegram notifications and/or Pushover notifications, neither are working, showing an error (500 Internal Server Error according to the console)

**Screenshots**
![image](https://user-images.githubusercontent.com/88262560/129456486-31b2fd48-5189-4075-ac52-88a6c11c44cd.png)
![image](https://user-images.githubusercontent.com/88262560/129456518-d5483da5-00c6-42a9-8b34-0e755fcef450.png)
![image](https://user-images.githubusercontent.com/88262560/129456540-6ae11d52-5727-4eee-8370-7bdeeedd13ab.png)

Am I doing something wrong here...?

**Comment by theyosh** [comment]
Hi,

Nope, this is not working. As I am struggling a bit with the amount of code to refactor, and as I do not use any social media anymore or other services like pusher or telegram, I am afraid that this will not be restored.

So, I am thinking of changing this, so that it all works with MQTT, where you then can at least create some own clients that push the info to Pusher or Telegram. So I make a more general notification system, and then it is for the user to integrate with Telegram of other systems.

Also, I am currently thinking of supporting Matrix somehow, so that you can 'chat' with TerrariumPI. And as Matrix also support all kind of bridges between Matrix and Telegram, Whatsapp, etc... It makes it easier for me to finish the notification part.

So for now, the notification part is not working. If you really need it, stick at version 3 for now.

**Comment by theyosh** [comment]
I added more information here: #597
