### ISSUE TITLE
[BUG:] Can't add AM2302 sensor

### ISSUE THREAD

**Issue by duenni** [theyosh/TerrariumPI#614]
**More info**
Hi,

I used version 3.x and did a new install of version 4 today. I screenshoted the settings of my sensors and try to add them in the new installation.

**Setup:**
 - TerrariumPI version: 4
 - Python version: 3
 - Raspberry PI: 3B

**Describe the bug**
I cannot add a AM2302 sensor:
```
2021-10-20 14:51:51,940 - WARNING - hardware.sensor       - Unable to load sensor AM2302 sensor humidity named 'sensor1_humidity' at address '11': 'NoneType' object has no attribute 'send', retrying in 0.5 seconds...
```
The address is correct (it worked in version 3), however I tried other addresses and always get this error.

**To Reproduce / Installation steps**
Try adding a AM2302 sensor with a correct address.

**Expected behavior**
Sensor should be identified and added to the sensors list.

**Screenshots**
That's what I see in the logs:
```
2021-10-20 14:51:51,940 - WARNING - hardware.sensor       - Unable to load sensor AM2302 sensor humidity named 'sensor1_humidity' at address '11': 'NoneType' object has no attribute 'send', retrying in 0.5 seconds...
```

**Additional context**
I can also see that the `owserver.service` is not running. But I don't have any 1-wire sensors so I am not sure if this is related to the problem.
I restarted multiple times to no avail. Scanning for new sensors also doesn't help.

Any ideas?
Thanks!

**Comment by theyosh** [comment]
Hmm, what address did you use? I see in the error 11. Is that the same address as used in TP3? Because I got a confirmation that this sensor should work. I do not own one myself, so I relied on other people for testing....

Owserver service is not needed for this. As this is a DHT like sensor.

So, could you see if there is a process running called: `/usr/bin/pigpiod` ? Because that is needed in order to readout the sensor. It should be running as my install script should installing that.
