### ISSUE TITLE
Cosmetic issue: Uptime on dashboard

### ISSUE THREAD

**Issue by Aapjes94** [theyosh/TerrariumPI#64]
I'm still setting everything up at the moment but noticed a quirk. The System Status bars overlap the uptime counter.

<img width="563" alt="screen shot 2017-12-12 at 22 26 40" src="https://user-images.githubusercontent.com/34491613/33909406-dbb0aa60-df8b-11e7-8ce1-223874cf476b.png"> 

It is a small cosmetic issue, which probably isn't even noticeable on a wide screen.

**Comment by theyosh** [comment]
Hmm, actual this is by design :P . I thought that the bars should go over the uptime. Because the last seconds are not that important. Else I have either to remove the cpu usage bars, make smaller font etc.

And CSS is not my strongest part in coding. And yes, I do have a wide screen :)

But what would you expect? Because for me it is not an issue. So I have a bit of a hard time to figure out what a good solution would be.

**Comment by Aapjes94** [comment]
I am not really experienced in CSS either, so I cannot really offer an alternative. I guess I shoud consider getting a wider screen :) 

Feel free to close the issue.

**Comment by theyosh** [comment]
goed, dan sluit ik de issue ;)
