### ISSUE TITLE
MQTT support?

### ISSUE THREAD

**Issue by iLLiac4** [theyosh/TerrariumPI#65]
Hi.
Is it possible to add MQTT support since there are so many esp2866 based sensors like the one from Sonoff or. wemos that could be really usefull in serving temperature, 230v relays,...
All the major firmware like espurna, easyesp,  tasmona support mqtt communication.
On raspberry pi it is easy to install mqtt broker like apt-get install mosquitto.

TNX

**Comment by theyosh** [comment]
In what way do you want support. I see that a espurna is a remote device. And that does support HTTP so my software should able to read out some information already.

But in order to control, I need to add code for adding them in my software. That could be an option. But my problem is that I do not use those devices. And making code for a device which I cannot test, it hard to do.

So could you explain a bit more what you are looking for?
