### ISSUE TITLE
[BUG]: "Current" temperature readout for enclosure stuck at 79.31F

### ISSUE THREAD

**Issue by threedom** [theyosh/TerrariumPI#710]
**Setup:**
 - TerrariumPI version: 4
 - Python version: 3
 - Raspberry PI: 4

**Describe the bug**
Both in the Enclosure view and in the Home Dashboard the temperature for my enclosure area "Heatmat" (a heating area that I run with a sensor) is stuck at 79.31F.
![image](https://user-images.githubusercontent.com/11461427/175160925-f1cdb108-8018-46dc-b8bc-740c69cd279b.png)

![image](https://user-images.githubusercontent.com/11461427/175160940-f4795d6a-5777-4236-8844-d53c80224cb8.png)

The actual measured temperature in the Sensors Temperature view is however accurate. 
![image](https://user-images.githubusercontent.com/11461427/175161062-de651a37-8e7f-4687-9556-4d7a03d9d4db.png)

To add further to the issue: The relay I control for the heatmat appears to be switching on despite being outside of the temperature range, since it seems to believe that the 79.31F are the actual temperature. SO it keeps switching on with ever 30s update, thereby overheating the terrarium.

![image](https://user-images.githubusercontent.com/11461427/175161750-36e5ebcf-4695-4f86-a35f-4c4024951a41.png)

Note:
When reloading the Sensors Temperature page, the relevant sensor shows 79.306F (roughly 79.31F) until the page has fully loaded and shows the accurate temperature. So it seems to me that the switch is being operated with this incorrect temperature but I don't know where that temperature is coming from.
![image](https://user-images.githubusercontent.com/11461427/175163653-59fa8b6d-dc84-4d56-b97a-f90f9790a932.png)

Similarly, the average temperature on the dashboard is stuck at 79.231F which is the average of the above (incorrect temperature readings): 
![image](https://user-images.githubusercontent.com/11461427/175163594-cb4817f1-da09-4d51-8cc3-754d056633e5.png)

for reference, here the accurate temperature readings (which show up after about 5 seconds on the Sensors page): 
![image](https://user-images.githubusercontent.com/11461427/175163854-30f79306-6b61-4953-a058-64729c5f57cc.png)

**Comment by theyosh** [comment]
Hmm, this is a bit strange. Can you post also the graphs of those sensors?

Also, could you post the area setup form? So I can see all the settings.

And can I advise to change the alarm values a bit so that the working range will be bigger. 0.3F is a very small range. So I would suggest a alarm min value of -2 of the wanted temperature, and alarm max value +2. So you have  range of 4F.
Also, make sure that the min and max values are at least 10F from the wanted value. If a readout is outside the min and max value, it will be ignored, and an old value is used.

The difference during loading is due to the fact that the last value of the graph is used initial, and then updated when the sensor has a new reading. But that should not affect the working/logic of the area. This is more a nasty GUI bug..

And, what happens when you restart the PI? Maybe a reboot/restart could fix it. At least this is not a known issue for me... and for now, I need some more info, before I can figure this out.

**Comment by theyosh** [comment]
Any updates? I need some more information in order to help.

**Comment by theyosh** [comment]
Hmm, these are strange things... but luckily you were able to fix it. So I close this issue now. Thanks for the update.
