### ISSUE TITLE
Changing static IP address

### ISSUE THREAD

**Issue by jezzalencko** [theyosh/TerrariumPI#825]
Hi @theyosh, I've tried changing the IP address and rebooting the tPi, however it won't change for some reason.
Any idea how I can force a static IP?

**Comment by theyosh** [comment]
Changing IP outside support of TerrariumPI. But a quick google search results: https://raspberrypi-guide.github.io/networking/set-up-static-ip-address

And keep the address `0.0.0.0` in the GUI. Because this means listen to the IP of the Pi. On change this value when you have multiple network devices on your PI

**Comment by theyosh** [comment]
Does the above help? There is not much I can do more.

Would like to close this issue.

**Comment by jezzalencko** [comment]
Haven’t had a chance to workout how to do this, but you can close the issue.
