### ISSUE TITLE
[FEATURE]: Toggle to enable/disable notifications in the "edit button" screen

### ISSUE THREAD

**Issue by chakachim** [theyosh/TerrariumPI#842]
**Is your feature request related to a problem? Please describe.**
I have started using the notification feature to alert me whenever the door is opened on the Terrarium. However it looks like there is no way (that I've found) to disable a button from notifying. As a result I get notified everytime the light sensor is triggered. 

**Describe the solution you'd like**
toggle button on the button edit screen that allows me to disable notifications.

**Additional context**

**Comment by theyosh** [comment]
Yeah, I think this can be done. Need some time to add it.

**Comment by theyosh** [comment]
Hi,

I added this option to sensor, relays and buttons. In order to test/use you need to update the code with `git pull` and rerun the installer. `sudo ./install.sh` as there new libraries being used for other new features.

After that, you can edit the button you want to disable from notification by disabling the notification setting.

**Comment by theyosh** [comment]
Oh, and make user TerrariumPI is stopped before updating.

**Comment by theyosh** [comment]
Any update on this? The new release is out, and this is released. So it should work. Could you confirm this?

**Comment by chakachim** [comment]
Just updated and tested. Everything is working great. Thank you for adding
this feature!

**Comment by theyosh** [comment]
Thanks for the feedback.
