### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by Barbara1984** [theyosh/TerrariumPI#88]
Hi, my Rasp finds no update under cdTerrariumPI> git pull, do I have to do something else?

**Comment by theyosh** [comment]
You probably downloaded the zip file. That cannot be updated with git.

Stop the software. Move the existing folder to a backup name. Make sure you do this all as user pi :

`mv TerrariumPI TerrariumPI.bak`

Then follow the installation steps for a git installation: https://github.com/theyosh/TerrariumPI#installation

Then before you reboot, copy the old settings.cfg and history.db file from the backup folder to the new folder.

And restart the Pi. You will then have a new installation with your existing config and history data. Be aware that the first restart will take about 5 minutes. This is due to the database update with the new version.

**Comment by Barbara1984** [comment]
Hi, thanks for your info but which folder I have to secure exactly because I do that on Filezilla :-)

**Comment by Barbara1984** [comment]
Only the settings.cfg or?

**Comment by theyosh** [comment]
and history.db

You should download those with filezilla. And upload back after the installation.

**Comment by Barbara1984** [comment]
![grafik](https://user-images.githubusercontent.com/34924591/35884132-e7dbb134-0b89-11e8-8c9e-cfe85dbfd5f5.png)

What is the problem, it can not start anymore?

**Comment by Barbara1984** [comment]
![grafik](https://user-images.githubusercontent.com/34924591/35884266-66e82c82-0b8a-11e8-8ce9-8d958dcd0654.png)

**Comment by theyosh** [comment]
Ok, sounds like configuration issues... Try a reboot.

If that does not help, remove the file settings.cfg and reboot again. Then you have to setup again your setup.

Else it is hard to explain what to do with only two pictures.

So reboot pi, and see what happens.

**Comment by Barbara1984** [comment]
![unbenannt](https://user-images.githubusercontent.com/34924591/35886615-f7b5b8c2-0b91-11e8-9a95-942bac1d15b4.png)

Can it be due to the permission? without Settings.cfg and history it starts.

**Comment by theyosh** [comment]
No, it is a code issue. But the quick fix now is that you leave the history.db file on the pi and remove the settings.cfg

And reboot. This will restart an empty system with old data. When you then add your sensors again it should pickup the old history.

You will have to wait about 5 minutes when you reboot the Pi, because the DB is being updated. That takes some time.

**Comment by Barbara1984** [comment]
Ok, thanks for your help, everything works again.

**Comment by theyosh** [comment]
Cool! Nice! Upgrades of configuration is a bit hard to test in code...
